import { useState, useEffect, useRef } from 'react';
import { 
  Save, Copy, Download, Upload, RotateCcw, X, ChevronDown, 
  ChevronUp, FileText, Settings, AlertCircle, CheckCircle
} from 'lucide-react';
import { useServerStore } from '../stores/serverStore';

interface ConfigEditorProps {
  serverId: string;
  onClose: () => void;
}

export function ConfigEditor({ serverId, onClose }: ConfigEditorProps) {
  const { servers } = useServerStore();
  const server = servers.find(s => s.id === serverId);
  
  const [configContent, setConfigContent] = useState('');
  const [originalContent, setOriginalContent] = useState('');
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [hasChanges, setHasChanges] = useState(false);
  const [activeTab, setActiveTab] = useState<'settings' | 'dedicated' | 'maps' | 'raw'>('settings');
  const [validationErrors, setValidationErrors] = useState<string[]>([]);
  const editorRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    if (server) {
      loadConfig();
    }
  }, [server]);

  const loadConfig = async () => {
    setIsLoading(true);
    try {
      const token = localStorage.getItem('rx-nexus-auth')
        ? JSON.parse(localStorage.getItem('rx-nexus-auth')!).state.token
        : null;

      const response = await fetch(`http://localhost:3001/api/servers/${serverId}/config`, {
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      });
      
      if (response.ok) {
        const data = await response.json();
        setConfigContent(data.content || '');
        setOriginalContent(data.content || '');
      } else {
        // Load default config template
        const defaultConfig = getDefaultConfig(server!);
        setConfigContent(defaultConfig);
        setOriginalContent(defaultConfig);
      }
    } catch (error) {
      const defaultConfig = getDefaultConfig(server!);
      setConfigContent(defaultConfig);
      setOriginalContent(defaultConfig);
    } finally {
      setIsLoading(false);
    }
  };

  const getDefaultConfig = (server: typeof server) => {
    return `# Armagetron Advanced Server Configuration
# Server: ${server?.name}
# Port: ${server?.port}
# Generated by RX-NEXUS

# Basic Server Settings
SERVER_NAME ${server?.name}
SERVER_PORT ${server?.port}
MAX_CLIENTS 16
MAX_CLIENTS_HI 0
MAX_IN_RATE 4000
MAX_OUT_RATE 4000

# Game Settings
GAME_TYPE 1
WIN_ZONE_DEATHS 1
WIN_ZONE_MIN_LAST_DEATH 30
WIN_ZONE_MIN_ROUND_TIME 30
WIN_ZONE_RADIUS 10

# Network
LISTEN_PORT ${server?.port}
LISTEN_IP 0.0.0.0

# Logging
LOG_LEVEL 2
LOG_FILE logs/server.log
LOG
ACCESS_LOG_FILE logs/accessLOG
CHAT_LOG_FILE logs/chatLOG
CONSOLE_LOG_FILE logs/consoleLOG

# Security
ADMIN_PASS changeme
USER_PASS 

# Physics
CYCLE_SPEED 30.0
CYCLE_ACCEL 12.0
CYCLE_BRAKE 0.1
CYCLE_RUBBER 10.0
CYCLE_RUBBER_MINDISTANCE 0.01
CYCLE_RUBBER_MINDISTANCE_RATIO 0.0001
CYCLE_RUBBER_MINDISTANCE_UNPREPARED 0.02
CYCLE_RUBBER_MINDISTANCE_RATIO_UNPREPARED 0.0002
CYCLE_RUBBER_LEGACY 0
CYCLE_DELAY 0.1
CYCLE_DELAY_TIMEBASED 1
CYCLE_WALLS_LENGTH 200
CYCLE_WALLS_STAY_UP_DELAY 10.0

# Arena
ARENA_SIZE 500
ARENA_AXES 4

# Camera
CAMERA_CUSTOM_BACK 15.0
CAMERA_CUSTOM_RISE 10.0
CAMERA_CUSTOM_PITCH -15.0
CAMERA_GLANCE_BACK 30.0
CAMERA_GLANCE_RISE 10.0
CAMERA_GLANCE_PITCH -30.0

# Team Settings
TEAM_MAX_PLAYERS 8
TEAM_BALANCE 1
TEAM_BALANCE_WITH_AIS 0
TEAM_ALLOW_SHUFFLE_UP 1

# AI Settings
AI_PLAYER 0
MAX_AI_PLAYERS 0
AI_DIFFICULTY 3

# Chat
CHAT_FLOOD_PROTECTION 1
CHAT_MAX_CHARS 200

# Voting
VOTING_TIMEOUT 30
VOTING_MIN_VOTERS 2
VOTING_KICK_MIN_VOTERS 3
VOTING_KICK_RATIO 0.6
VOTING_SUSPEND_MIN_VOTERS 3
VOTING_SUSPEND_RATIO 0.6

# Map Rotation (empty = no rotation)
MAP_ROTATION_1 
MAP_ROTATION_2 
MAP_ROTATION_3 
MAP_ROTATION_4 
MAP_ROTATION_5 

# Resource Settings
RESOURCE_REPOSITORY_SERVER http://resource.armagetronad.net/resource/
RESOURCE_REPOSITORY_CLIENT http://resource.armagetronad.net/resource/
DOWNLOAD_RATE 1000
`;
  };

  const validateConfig = (content: string) => {
    const errors: string[] = [];
    const lines = content.split('\n');
    
    lines.forEach((line, index) => {
      const trimmed = line.trim();
      if (trimmed && !trimmed.startsWith('#')) {
        const parts = trimmed.split(/\s+/);
        if (parts.length < 2) {
          errors.push(`Line ${index + 1}: Invalid format - expected "KEY VALUE"`);
        }
      }
    });
    
    // Check required settings
    const requiredKeys = ['SERVER_NAME', 'SERVER_PORT', 'MAX_CLIENTS'];
    requiredKeys.forEach(key => {
      if (!content.includes(key)) {
        errors.push(`Missing required setting: ${key}`);
      }
    });
    
    setValidationErrors(errors);
    return errors.length === 0;
  };

  const handleSave = async () => {
    if (!validateConfig(configContent)) return;
    
    setIsSaving(true);
    try {
      const token = localStorage.getItem('rx-nexus-auth')
        ? JSON.parse(localStorage.getItem('rx-nexus-auth')!).state.token
        : null;

      const response = await fetch(`http://localhost:3001/api/servers/${serverId}/config`, {
        method: 'POST',
        headers: { 
          'Content-Type': 'application/json', 
          ...(token ? { Authorization: `Bearer ${token}` } : {}) 
        },
        body: JSON.stringify({ content: configContent }),
      });
      
      if (response.ok) {
        setOriginalContent(configContent);
        setHasChanges(false);
        // Show success toast
      } else {
        throw new Error('Failed to save config');
      }
    } catch (error) {
      console.error('Failed to save config:', error);
    } finally {
      setIsSaving(false);
    }
  };

  const handleContentChange = (content: string) => {
    setConfigContent(content);
    setHasChanges(content !== originalContent);
  };

  const handleRevert = () => {
    setConfigContent(originalContent);
    setHasChanges(false);
  };

  const handleDownload = () => {
    const blob = new Blob([configContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${server?.name}-settings.cfg`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(configContent);
  };

  const formatConfig = () => {
    // Basic formatting - align values
    const lines = configContent.split('\n');
    const formatted = lines.map(line => {
      const trimmed = line.trim();
      if (trimmed && !trimmed.startsWith('#')) {
        const parts = trimmed.split(/\s+/);
        if (parts.length >= 2) {
          const key = parts[0];
          const value = parts.slice(1).join(' ');
          return `${key.padEnd(30)} ${value}`;
        }
      }
      return line;
    });
    setConfigContent(formatted.join('\n'));
  };

  if (!server) {
    return (
      <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
        <div className="bg-gray-900 border border-gray-700 rounded-xl p-6 max-w-md w-full mx-4">
          <h2 className="text-xl font-bold text-white mb-4">Server not found</h2>
          <button onClick={onClose} className="px-4 py-2 bg-primary hover:bg-primary/90 text-white rounded-lg">
            Close
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="fixed inset-0 z-50 flex">
      <div className="absolute inset-0 bg-black/50" onClick={onClose} />
      <div className="relative w-full max-w-4xl h-[85vh] max-h-[85vh] bg-gray-900 flex flex-col overflow-hidden mx-auto my-4 rounded-xl border border-gray-700 shadow-2xl">
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-gray-700">
          <div className="flex items-center gap-3">
            <button onClick={onClose} className="p-2 hover:bg-gray-800 rounded-lg transition-colors">
              <X className="w-5 h-5 text-gray-400" />
            </button>
            <div>
              <h2 className="text-xl font-bold text-white">Config Editor - {server.name}</h2>
              <p className="text-sm text-gray-400">settings.cfg • Port: {server.port}</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleRevert}
              disabled={!hasChanges || isSaving}
              className="px-3 py-1.5 bg-gray-700 hover:bg-gray-600 text-white text-sm font-medium rounded-lg transition-colors disabled:opacity-50 flex items-center gap-1.5"
            >
              <RotateCcw className="w-4 h-4" />
              Revert
            </button>
            <button
              onClick={handleSave}
              disabled={!hasChanges || isSaving || validationErrors.length > 0}
              className="px-3 py-1.5 bg-primary hover:bg-primary/90 text-white text-sm font-medium rounded-lg transition-colors disabled:opacity-50 flex items-center gap-1.5"
            >
              <Save className="w-4 h-4" />
              {isSaving ? 'Saving...' : 'Save'}
            </button>
          </div>
        </div>

        {/* Validation Errors */}
        {validationErrors.length > 0 && (
          <div className="px-4 py-2 bg-red-500/10 border-b border-red-500/20">
            <div className="flex items-center gap-2 text-red-400 text-sm">
              <AlertCircle className="w-4 h-4" />
              <span>{validationErrors.length} validation error(s)</span>
              <button onClick={() => setActiveTab('raw')} className="ml-auto text-xs underline hover:text-red-300">
                View
              </button>
            </div>
          </div>
        )}

        {/* Tabs */}
        <div className="border-b border-gray-700 flex px-4">
          {[
            { id: 'settings', label: 'Settings', icon: Settings },
            { id: 'dedicated', label: 'Dedicated', icon: FileText },
            { id: 'maps', label: 'Maps', icon: FileText },
            { id: 'raw', label: 'Raw', icon: FileText },
          ].map(({ id, label, icon: Icon }) => (
            <button
              key={id}
              onClick={() => setActiveTab(id as typeof activeTab)}
              className={`flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-t-lg transition-colors ${
                activeTab === id
                  ? 'bg-gray-800 text-primary border-b-2 border-primary'
                  : 'text-gray-400 hover:text-gray-200 hover:bg-gray-800/50'
              }`}
            >
              <Icon className="w-4 h-4" />
              {label}
            </button>
          ))}
        </div>

        {/* Toolbar */}
        <div className="px-4 py-2 border-b border-gray-700 flex items-center gap-2 bg-gray-800/50">
          <div className="flex items-center gap-2">
            <button
              onClick={formatConfig}
              className="px-3 py-1.5 bg-gray-700 hover:bg-gray-600 text-white text-sm rounded-lg transition-colors flex items-center gap-1.5"
              title="Format config"
            >
              <RotateCcw className="w-4 h-4" />
              Format
            </button>
            <button
              onClick={handleCopy}
              className="px-3 py-1.5 bg-gray-700 hover:bg-gray-600 text-white text-sm rounded-lg transition-colors flex items-center gap-1.5"
              title="Copy to clipboard"
            >
              <Copy className="w-4 h-4" />
              Copy
            </button>
            <button
              onClick={handleDownload}
              className="px-3 py-1.5 bg-gray-700 hover:bg-gray-600 text-white text-sm rounded-lg transition-colors flex items-center gap-1.5"
              title="Download config"
            >
              <Download className="w-4 h-4" />
              Download
            </button>
          </div>
          <div className="flex-1" />
          <span className="text-xs text-gray-500">
            {configContent.split('\n').length} lines • {configContent.length} chars
          </span>
        </div>

        {/* Editor */}
        <div className="flex-1 overflow-hidden p-4">
          <textarea
            ref={editorRef}
            value={configContent}
            onChange={(e) => handleContentChange(e.target.value)}
            className="w-full h-full font-mono text-sm bg-black border border-gray-700 rounded-lg p-4 text-white focus:outline-none focus:ring-2 focus:ring-primary resize-none"
            placeholder="Loading configuration..."
            spellCheck={false}
            disabled={isLoading}
          />
        </div>

        {/* Status Bar */}
        <div className="px-4 py-2 border-t border-gray-700 bg-gray-800/50 flex items-center justify-between text-xs text-gray-400">
          <div className="flex items-center gap-4">
            <span>Ln {editorRef.current?.value.substring(0, editorRef.current?.selectionStart).split('\n').length || 1}</span>
            <span>Col {editorRef.current?.selectionStart - editorRef.current?.value.lastIndexOf('\n', editorRef.current?.selectionStart - 1) || 1}</span>
            <span>UTF-8</span>
            <span>CFG</span>
          </div>
          <div className="flex items-center gap-2">
            {hasChanges && (
              <span className="flex items-center gap-1 text-yellow-400">
                <AlertCircle className="w-3 h-3" />
                Unsaved changes
              </span>
            )}
            {!hasChanges && configContent && (
              <span className="flex items-center gap-1 text-green-400">
                <CheckCircle className="w-3 h-3" />
                Saved
              </span>
            )}
            {validationErrors.length > 0 && (
              <span className="flex items-center gap-1 text-red-400">
                <AlertCircle className="w-3 h-3" />
                {validationErrors.length} error(s)
              </span>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}