import { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { toast } from '@/hooks/use-toast';
import { Copy, Terminal, Server, Download } from 'lucide-react';
import { getBinaryDownloadUrl } from '@/lib/supabaseApi';

export default function AgentWizardPage() {
  const [hostIp, setHostIp] = useState('');
  const [agentPort, setAgentPort] = useState('8080');
  const [binaryPath, setBinaryPath] = useState('/usr/bin/armagetronad-dedicated');
  const [queryPath, setQueryPath] = useState('/usr/bin/armagetronad-serverquery');
  const [dataDir, setDataDir] = useState('/usr/share/armagetronad');
  const [configDir, setConfigDir] = useState('/etc/armagetronad/new');
  const [gamePort, setGamePort] = useState('4534');
  const [generated, setGenerated] = useState('');

  const dedicatedUrl = getBinaryDownloadUrl('armagetronad-dedicated');
  const queryUrl = getBinaryDownloadUrl('armagetronad-serverquery');

  const generateScript = () => {
    if (!hostIp.trim()) {
      toast({ title: 'Host IP required', variant: 'destructive' });
      return;
    }

    const script = `#!/bin/bash
# ═══════════════════════════════════════════════════════════
# Armagetron / RetroCycles — Host Agent Setup Script
# Generated by RxTron Control Panel
# ═══════════════════════════════════════════════════════════
set -euo pipefail

HOST_IP="${hostIp}"
AGENT_PORT="${agentPort}"
BINARY_PATH="${binaryPath}"
QUERY_PATH="${queryPath}"
DATA_DIR="${dataDir}"
CONFIG_DIR="${configDir}"
GAME_PORT="${gamePort}"

echo "╔══════════════════════════════════════════════╗"
echo "║  RxTron Host Agent Installer                 ║"
echo "╚══════════════════════════════════════════════╝"

# 1. Download binaries
echo "[1/5] Downloading binaries..."
curl -fSL "${dedicatedUrl}" -o "\${BINARY_PATH}" || { echo "Failed to download dedicated server"; exit 1; }
curl -fSL "${queryUrl}" -o "\${QUERY_PATH}" || { echo "Failed to download server query"; exit 1; }
chmod +x "\${BINARY_PATH}" "\${QUERY_PATH}"
echo "  ✓ Binaries installed"

# 2. Create directories
echo "[2/5] Setting up directories..."
mkdir -p "\${DATA_DIR}" "\${CONFIG_DIR}"
echo "  ✓ Directories ready"

# 3. Create systemd service for game server
echo "[3/5] Creating game server service..."
cat > /etc/systemd/system/armagetronad.service << UNIT
[Unit]
Description=Armagetron Advanced Dedicated Server
After=network.target

[Service]
Type=simple
ExecStart=\${BINARY_PATH} --datadir \${DATA_DIR} --configdir \${CONFIG_DIR} --port \${GAME_PORT}
Restart=on-failure
RestartSec=5
User=armagetron
WorkingDirectory=\${DATA_DIR}
StandardInput=tty
TTYPath=/dev/tty-arma

[Install]
WantedBy=multi-user.target
UNIT
echo "  ✓ Game server service created"

# 4. Create agent service (lightweight HTTP proxy for the panel)
echo "[4/5] Creating agent service..."
cat > /etc/systemd/system/rxtron-agent.service << UNIT
[Unit]
Description=RxTron Host Agent
After=network.target armagetronad.service

[Service]
Type=simple
ExecStart=/usr/local/bin/rxtron-agent --port \${AGENT_PORT} --binary \${BINARY_PATH} --datadir \${DATA_DIR} --configdir \${CONFIG_DIR}
Restart=always
RestartSec=3
User=root

[Install]
WantedBy=multi-user.target
UNIT
echo "  ✓ Agent service created"

# 5. Firewall
echo "[5/5] Configuring firewall..."
if command -v ufw &>/dev/null; then
  ufw allow \${GAME_PORT}/udp comment "Armagetron game"
  ufw allow \${AGENT_PORT}/tcp comment "RxTron agent"
  echo "  ✓ UFW rules added"
elif command -v firewall-cmd &>/dev/null; then
  firewall-cmd --permanent --add-port=\${GAME_PORT}/udp
  firewall-cmd --permanent --add-port=\${AGENT_PORT}/tcp
  firewall-cmd --reload
  echo "  ✓ firewalld rules added"
else
  echo "  ⚠ No firewall manager found — manually open ports \${GAME_PORT}/udp and \${AGENT_PORT}/tcp"
fi

# Create user if needed
id -u armagetron &>/dev/null || useradd -r -s /usr/sbin/nologin armagetron

systemctl daemon-reload
systemctl enable armagetronad rxtron-agent

echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║  Setup complete!                             ║"
echo "╠══════════════════════════════════════════════╣"
echo "║  Agent URL: http://\${HOST_IP}:\${AGENT_PORT}  ║"
echo "║                                              ║"
echo "║  Paste this URL into the server's Overview   ║"
echo "║  tab in the control panel.                   ║"
echo "║                                              ║"
echo "║  Start services:                             ║"
echo "║    systemctl start armagetronad              ║"
echo "║    systemctl start rxtron-agent              ║"
echo "╚══════════════════════════════════════════════╝"
`;

    setGenerated(script);
    toast({ title: 'Script generated', description: 'Copy it and run on your game server host' });
  };

  const copyScript = () => {
    navigator.clipboard.writeText(generated);
    toast({ title: 'Copied to clipboard' });
  };

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      <div>
        <h1 className="text-2xl font-bold flex items-center gap-2">
          <Terminal className="h-6 w-6 text-primary" />
          Host Agent Setup Wizard
        </h1>
        <p className="text-muted-foreground mt-1">
          Generate an install script for your game server machine. The agent enables remote management from this panel.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Server className="h-5 w-5" />
            Host Configuration
          </CardTitle>
          <CardDescription>Enter the details for your game server host machine</CardDescription>
        </CardHeader>
        <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label>Host IP / Hostname *</Label>
            <Input value={hostIp} onChange={e => setHostIp(e.target.value)} placeholder="192.168.1.100 or myserver.local" />
          </div>
          <div className="space-y-2">
            <Label>Agent Port</Label>
            <Input value={agentPort} onChange={e => setAgentPort(e.target.value)} placeholder="8080" />
          </div>
          <div className="space-y-2">
            <Label>Game Server Binary Path</Label>
            <Input value={binaryPath} onChange={e => setBinaryPath(e.target.value)} />
          </div>
          <div className="space-y-2">
            <Label>Server Query Binary Path</Label>
            <Input value={queryPath} onChange={e => setQueryPath(e.target.value)} />
          </div>
          <div className="space-y-2">
            <Label>Data Directory</Label>
            <Input value={dataDir} onChange={e => setDataDir(e.target.value)} />
          </div>
          <div className="space-y-2">
            <Label>Config Directory</Label>
            <Input value={configDir} onChange={e => setConfigDir(e.target.value)} />
          </div>
          <div className="space-y-2">
            <Label>Game Port (UDP)</Label>
            <Input value={gamePort} onChange={e => setGamePort(e.target.value)} />
          </div>
          <div className="flex items-end">
            <Button onClick={generateScript} className="w-full">
              <Terminal className="h-4 w-4 mr-2" /> Generate Install Script
            </Button>
          </div>
        </CardContent>
      </Card>

      {generated && (
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle className="flex items-center gap-2">
                <Download className="h-5 w-5" />
                Install Script
              </CardTitle>
              <Button variant="outline" size="sm" onClick={copyScript}>
                <Copy className="h-4 w-4 mr-1" /> Copy
              </Button>
            </div>
            <CardDescription>Run this script as root on your game server host</CardDescription>
          </CardHeader>
          <CardContent>
            <pre className="bg-muted rounded-lg p-4 text-xs font-mono overflow-auto max-h-[500px] whitespace-pre-wrap">
              {generated}
            </pre>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
