import { ServerConfig, ServerInstance, PortAllocation } from '@rx/shared-types';
import * as fs from 'fs';
import * as path from 'path';

const INSTANCES_BASE_PATH = process.env.INSTANCES_PATH || path.resolve(process.cwd(), 'instances');
const PORT_RANGE_START = parseInt(process.env.PORT_RANGE_START || '4534', 10);
const PORT_RANGE_END = parseInt(process.env.PORT_RANGE_END || '5000', 10);

// Export the allocated ports map for external access
export const allocatedPorts = new Map<number, string>();
let nextPort = PORT_RANGE_START;

function ensureInstancesDirectory(): void {
  if (!fs.existsSync(INSTANCES_BASE_PATH)) {
    fs.mkdirSync(INSTANCES_BASE_PATH, { recursive: true, mode: 0o755 });
  }
}

function getInstancePath(instanceId: string): string {
  return path.join(INSTANCES_BASE_PATH, instanceId);
}

function getConfigPath(instanceId: string): string {
  return path.join(getInstancePath(instanceId), 'config');
}

function getLogsPath(instanceId: string): string {
  return path.join(getInstancePath(instanceId), 'logs');
}

export function allocatePort(): number {
  if (nextPort > PORT_RANGE_END) {
    nextPort = PORT_RANGE_START;
  }

  let attempts = 0;
  while (allocatedPorts.has(nextPort) && attempts < PORT_RANGE_END - PORT_RANGE_START) {
    nextPort++;
    if (nextPort > PORT_RANGE_END) {
      nextPort = PORT_RANGE_START;
    }
    attempts++;
  }

  if (attempts >= PORT_RANGE_END - PORT_RANGE_START) {
    throw new Error('No available ports in range');
  }

  const port = nextPort;
  nextPort++;
  return port;
}

export function reservePort(port: number, instanceId: string): boolean {
  if (port < PORT_RANGE_START || port > PORT_RANGE_END) {
    return false;
  }
  if (allocatedPorts.has(port)) {
    return false;
  }
  allocatedPorts.set(port, instanceId);
  return true;
}

export function releasePort(port: number): void {
  allocatedPorts.delete(port);
}

export function getAllocatedPorts(): PortAllocation[] {
  const allocations: PortAllocation[] = [];
  for (const [port, instanceId] of allocatedPorts.entries()) {
    allocations.push({
      port,
      instanceId,
      allocatedAt: new Date(),
    });
  }
  return allocations;
}

export function createInstance(config: ServerConfig): string {
  ensureInstancesDirectory();

  const instanceId = crypto.randomUUID();
  const port = allocatePort();

  const instancePath = getInstancePath(instanceId);
  const configPath = getConfigPath(instanceId);
  const logsPath = getLogsPath(instanceId);

  fs.mkdirSync(instancePath, { recursive: true, mode: 0o755 });
  fs.mkdirSync(configPath, { recursive: true, mode: 0o755 });
  fs.mkdirSync(logsPath, { recursive: true, mode: 0o755 });

  fs.writeFileSync(
    path.join(logsPath, 'stdout.log'),
    '',
    { mode: 0o644 }
  );
  fs.writeFileSync(
    path.join(logsPath, 'stderr.log'),
    '',
    { mode: 0o644 }
  );

  generateSettings(instanceId, config);

  reservePort(port, instanceId);

  return instanceId;
}

export function deleteInstance(instanceId: string): void {
  const instancePath = getInstancePath(instanceId);

  if (!fs.existsSync(instancePath)) {
    throw new Error(`Instance ${instanceId} does not exist`);
  }

  const settingsPath = path.join(getConfigPath(instanceId), 'settings.cfg');
  if (fs.existsSync(settingsPath)) {
    const content = fs.readFileSync(settingsPath, 'utf-8');
    const portMatch = content.match(/PORT\s+(\d+)/i);
    if (portMatch) {
      const port = parseInt(portMatch[1], 10);
      releasePort(port);
    }
  }

  fs.rmSync(instancePath, { recursive: true, force: true });
}

export function generateSettings(instanceId: string, config: ServerConfig): void {
  const configPath = getConfigPath(instanceId);
  const settingsPath = path.join(configPath, 'settings.cfg');

  const port = Array.from(allocatedPorts.entries())
    .find(([_, id]) => id === instanceId)?.[0];

  if (!port) {
    throw new Error(`No port allocated for instance ${instanceId}`);
  }

  const settings = [
    `# Armagetron Advanced Server Configuration`,
    `# Generated by RX-ECOSYSTEM Instance Factory`,
    `# Instance: ${instanceId}`,
    `# Name: ${config.name}`,
    `# Game Mode: ${config.gameMode}`,
    ``,
    `SERVER_NAME ${config.name}`,
    `PORT ${port}`,
    `MAX_PLAYERS ${config.maxPlayers}`,
    `TALK_TO_MASTER 1`,
    ``,
  ];

  if (config.gameMode) {
    settings.push(`# Game mode: ${config.gameMode}`);
  }

  if (config.mapRotation && config.mapRotation.length > 0) {
    settings.push(`MAP_ROTATION ${config.mapRotation.join(' ')}`);
    settings.push(``);
  }

  if (config.customCfg) {
    for (const [key, value] of Object.entries(config.customCfg)) {
      settings.push(`${key.toUpperCase()} ${value}`);
    }
    settings.push(``);
  }

  settings.push(`AUTO_RESTART ${config.autoRestart ? '1' : '0'}`);

  fs.mkdirSync(configPath, { recursive: true });
  fs.writeFileSync(settingsPath, settings.join('\n'), { mode: 0o644 });
}

export function getInstanceConfig(instanceId: string): ServerConfig | null {
  const settingsPath = path.join(getConfigPath(instanceId), 'settings.cfg');

  if (!fs.existsSync(settingsPath)) {
    return null;
  }

  const content = fs.readFileSync(settingsPath, 'utf-8');
  const lines = content.split('\n');

  const config: Partial<ServerConfig> = {
    customCfg: {},
  };

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const [key, ...valueParts] = trimmed.split(/\s+/);
    const value = valueParts.join(' ');

    switch (key.toUpperCase()) {
      case 'SERVER_NAME':
        config.name = value;
        break;
      case 'PORT':
        config.maxPlayers = parseInt(value, 10);
        break;
      case 'MAX_PLAYERS':
        config.maxPlayers = parseInt(value, 10);
        break;
      case 'GAME_MODE':
        config.gameMode = value as ServerConfig['gameMode'];
        break;
      case 'AUTO_RESTART':
        config.autoRestart = value === '1';
        break;
      case 'MAP_ROTATION':
        config.mapRotation = value.split(/\s+/);
        break;
      default:
        if (config.customCfg) {
          config.customCfg[key] = value;
        }
    }
  }

  return config as ServerConfig;
}

export function listInstances(): string[] {
  ensureInstancesDirectory();
  return fs.readdirSync(INSTANCES_BASE_PATH)
    .filter(name => fs.statSync(path.join(INSTANCES_BASE_PATH, name)).isDirectory());
}

export function instanceExists(instanceId: string): boolean {
  return fs.existsSync(getInstancePath(instanceId));
}

export function getInstanceBasePath(instanceId: string): string {
  return getInstancePath(instanceId);
}

export function getInstanceLogsPath(instanceId: string): string {
  return getLogsPath(instanceId);
}

export function getInstanceConfigPath(instanceId: string): string {
  return getConfigPath(instanceId);
}

export function getInstancesBasePath(): string {
  return INSTANCES_BASE_PATH;
}

// Factory function
export function createInstanceFactory(): {
  create: typeof createInstance;
  delete: typeof deleteInstance;
  listInstances: typeof listInstances;
  getInstanceConfig: typeof getInstanceConfig;
  allocatedPorts: typeof allocatedPorts;
} {
  return {
    create: createInstance,
    delete: deleteInstance,
    listInstances,
    getInstanceConfig,
    allocatedPorts,
  };
}
